name = "cbc"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxzIYgDsxadSUYUr5X-6pG65W6-IeX14OJoUPe7CofdHDK8TDBsTeC_DUIYuS6Duzoa/exec"
